name: "Cache Nix Builds"
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: flyio
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build -A ruby_2_7_4
    - run: nix-shell --run "echo OK"

